version: '3'

services:
   db:
     platform: linux/x86_64
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
       - "./db-data/install_wordpress.sql:/docker-entrypoint-initdb.d/install_wordpress.sql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=wordpress
      - PMA_PASSWORD=wordpress
    ports:
      - "3000:80"

   wordpress:
     build: ./wordpress
     depends_on:
       - db
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
            - ./wp:/var/www/html
            # - ./wp-content:/var/www/html/wp-content
volumes:
    db_data: